### ISSUE TITLE
Unable to execute save() on local hosted Baqend

### ISSUE THREAD

**Issue by TiJac** [Baqend/guide#2]
There seems to be a bug with the local hosted version of Baqend.

I downloaded the current version (baqend-0.11.1-win-x64.zip) and started it. On executing the tutorial code with this local process (connected to http://localhost:8080) a save() of the Todo always fails (as one could see on the attached screenshot)
![screenshot 3](https://cloud.githubusercontent.com/assets/7216857/11590139/7e1fa73c-9a8e-11e5-8546-26066aa58fd9.png)

This is the 400 (Bad Request) Response body:

    {"className":"info.orestes.rest.error.BadRequest","message":"The body can't be processed","stackTrace":[{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":297},{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":272},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readSingleEntity","lineNumber":125},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readEntity","lineNumber":106},{"fileName":"DbBucket.java","className":"info.orestes.server.resource.db.DbBucket","methodName":"doPostAsync","lineNumber":101},{"fileName":"RestServlet.java","className":"info.orestes.rest.RestServlet","methodName":"service","lineNumber":370},{"fileName":"BaseResource.java","className":"info.orestes.server.resource.BaseResource","methodName":"service","lineNumber":31},{"fileName":"RestServletHandler.java","className":"info.orestes.rest.service.RestServletHandler","methodName":"handle","lineNumber":16},{"fileName":"RestHandler.java","className":"info.orestes.rest.service.RestHandler","methodName":"handle","lineNumber":18},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"RestRouter.java","className":"info.orestes.rest.service.RestRouter","methodName":"handle","lineNumber":98},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1160},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doScope","lineNumber":1094},{"fileName":"ScopedHandler.java","className":"org.eclipse.jetty.server.handler.ScopedHandler","methodName":"handle","lineNumber":141},{"fileName":"HandlerCollection.java","className":"org.eclipse.jetty.server.handler.HandlerCollection","methodName":"handle","lineNumber":109},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"Server.java","className":"org.eclipse.jetty.server.Server","methodName":"handle","lineNumber":517},{"fileName":"HttpChannel.java","className":"org.eclipse.jetty.server.HttpChannel","methodName":"handle","lineNumber":306},{"fileName":"HttpConnection.java","className":"org.eclipse.jetty.server.HttpConnection","methodName":"onFillable","lineNumber":242},{"fileName":"AbstractConnection.java","className":"org.eclipse.jetty.io.AbstractConnection$ReadCallback","methodName":"succeeded","lineNumber":261},{"fileName":"FillInterest.java","className":"org.eclipse.jetty.io.FillInterest","methodName":"fillable","lineNumber":95},{"fileName":"SelectChannelEndPoint.java","className":"org.eclipse.jetty.io.SelectChannelEndPoint$2","methodName":"run","lineNumber":75},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"produceAndRun","lineNumber":213},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"run","lineNumber":147},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":654},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":572},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}],"cause":{"className":"java.lang.IllegalArgumentException","message":"The formatted objectId is invalid.","stackTrace":[{"fileName":"ObjectRef.java","className":"info.orestes.common.typesystem.ObjectRef","methodName":"parse","lineNumber":190},{"fileName":"JsonObjectConverter.java","className":"info.orestes.rest.conversion.json.JsonObjectConverter","methodName":"toObject","lineNumber":153},{"fileName":"JsonObjectConverter.java","className":"info.orestes.rest.conversion.json.JsonObjectConverter","methodName":"toObject","lineNumber":20},{"fileName":"JsonFormat.java","className":"info.orestes.rest.conversion.format.JsonFormat$2","methodName":"read","lineNumber":100},{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":295},{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":272},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readSingleEntity","lineNumber":125},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readEntity","lineNumber":106},{"fileName":"DbBucket.java","className":"info.orestes.server.resource.db.DbBucket","methodName":"doPostAsync","lineNumber":101},{"fileName":"RestServlet.java","className":"info.orestes.rest.RestServlet","methodName":"service","lineNumber":370},{"fileName":"BaseResource.java","className":"info.orestes.server.resource.BaseResource","methodName":"service","lineNumber":31},{"fileName":"RestServletHandler.java","className":"info.orestes.rest.service.RestServletHandler","methodName":"handle","lineNumber":16},{"fileName":"RestHandler.java","className":"info.orestes.rest.service.RestHandler","methodName":"handle","lineNumber":18},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"RestRouter.java","className":"info.orestes.rest.service.RestRouter","methodName":"handle","lineNumber":98},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1160},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doScope","lineNumber":1094},{"fileName":"ScopedHandler.java","className":"org.eclipse.jetty.server.handler.ScopedHandler","methodName":"handle","lineNumber":141},{"fileName":"HandlerCollection.java","className":"org.eclipse.jetty.server.handler.HandlerCollection","methodName":"handle","lineNumber":109},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"Server.java","className":"org.eclipse.jetty.server.Server","methodName":"handle","lineNumber":517},{"fileName":"HttpChannel.java","className":"org.eclipse.jetty.server.HttpChannel","methodName":"handle","lineNumber":306},{"fileName":"HttpConnection.java","className":"org.eclipse.jetty.server.HttpConnection","methodName":"onFillable","lineNumber":242},{"fileName":"AbstractConnection.java","className":"org.eclipse.jetty.io.AbstractConnection$ReadCallback","methodName":"succeeded","lineNumber":261},{"fileName":"FillInterest.java","className":"org.eclipse.jetty.io.FillInterest","methodName":"fillable","lineNumber":95},{"fileName":"SelectChannelEndPoint.java","className":"org.eclipse.jetty.io.SelectChannelEndPoint$2","methodName":"run","lineNumber":75},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"produceAndRun","lineNumber":213},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"run","lineNumber":147},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":654},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":572},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}],"cause":{"className":"java.lang.StringIndexOutOfBoundsException","message":"String index out of range: -1","stackTrace":[{"fileName":"String.java","className":"java.lang.String","methodName":"substring","lineNumber":1967},{"fileName":"ObjectRef.java","className":"info.orestes.common.typesystem.ObjectRef","methodName":"parse","lineNumber":170},{"fileName":"JsonObjectConverter.java","className":"info.orestes.rest.conversion.json.JsonObjectConverter","methodName":"toObject","lineNumber":153},{"fileName":"JsonObjectConverter.java","className":"info.orestes.rest.conversion.json.JsonObjectConverter","methodName":"toObject","lineNumber":20},{"fileName":"JsonFormat.java","className":"info.orestes.rest.conversion.format.JsonFormat$2","methodName":"read","lineNumber":100},{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":295},{"fileName":"ConverterService.java","className":"info.orestes.rest.conversion.ConverterService","methodName":"toObject","lineNumber":272},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readSingleEntity","lineNumber":125},{"fileName":"RestRequest.java","className":"info.orestes.rest.service.RestRequest","methodName":"readEntity","lineNumber":106},{"fileName":"DbBucket.java","className":"info.orestes.server.resource.db.DbBucket","methodName":"doPostAsync","lineNumber":101},{"fileName":"RestServlet.java","className":"info.orestes.rest.RestServlet","methodName":"service","lineNumber":370},{"fileName":"BaseResource.java","className":"info.orestes.server.resource.BaseResource","methodName":"service","lineNumber":31},{"fileName":"RestServletHandler.java","className":"info.orestes.rest.service.RestServletHandler","methodName":"handle","lineNumber":16},{"fileName":"RestHandler.java","className":"info.orestes.rest.service.RestHandler","methodName":"handle","lineNumber":18},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"RestRouter.java","className":"info.orestes.rest.service.RestRouter","methodName":"handle","lineNumber":98},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1160},{"fileName":"ContextHandler.java","className":"org.eclipse.jetty.server.handler.ContextHandler","methodName":"doScope","lineNumber":1094},{"fileName":"ScopedHandler.java","className":"org.eclipse.jetty.server.handler.ScopedHandler","methodName":"handle","lineNumber":141},{"fileName":"HandlerCollection.java","className":"org.eclipse.jetty.server.handler.HandlerCollection","methodName":"handle","lineNumber":109},{"fileName":"HandlerWrapper.java","className":"org.eclipse.jetty.server.handler.HandlerWrapper","methodName":"handle","lineNumber":119},{"fileName":"Server.java","className":"org.eclipse.jetty.server.Server","methodName":"handle","lineNumber":517},{"fileName":"HttpChannel.java","className":"org.eclipse.jetty.server.HttpChannel","methodName":"handle","lineNumber":306},{"fileName":"HttpConnection.java","className":"org.eclipse.jetty.server.HttpConnection","methodName":"onFillable","lineNumber":242},{"fileName":"AbstractConnection.java","className":"org.eclipse.jetty.io.AbstractConnection$ReadCallback","methodName":"succeeded","lineNumber":261},{"fileName":"FillInterest.java","className":"org.eclipse.jetty.io.FillInterest","methodName":"fillable","lineNumber":95},{"fileName":"SelectChannelEndPoint.java","className":"org.eclipse.jetty.io.SelectChannelEndPoint$2","methodName":"run","lineNumber":75},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"produceAndRun","lineNumber":213},{"fileName":"ExecuteProduceConsume.java","className":"org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume","methodName":"run","lineNumber":147},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":654},{"fileName":"QueuedThreadPool.java","className":"org.eclipse.jetty.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":572},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}]}},"status":400,"reason":"Bad Request"}

Of course I created the schema of a Todo in advance: 
![screenshot 4](https://cloud.githubusercontent.com/assets/7216857/11590765/dc8dde7a-9a92-11e5-9ceb-542378b633a4.png)

What I've tried so far and didn't work:
- Edit the hosts file to get a more common url (http://xyz.local:8080)
- use local hosted version of the SDK
- use a html file with the javascript code and open that one in chrome
- host this html file by xampp

What might be interesting:
- creating in Dashboard works fine. Here are both Requests and an Issue might be the difference in the id:

Request Body Dashboard:

    {
      "listId":"blubb",
      "name":"bla",
      "active":true,
      "done":null,
      "activities":null,
      "id":"/db/Todo/cf9cd933-5769-4265-aa9b-f2f3cdede765",
      "acl":
      {
        "read":{},
        "write":{}
      }
    }

Request Body SDK:

    {
      "listId":null,
      "name":"My Todo",
      "active":null,
      "done":null,
      "activities":null,
      "id":"1bf41ce8-5886-4a76-8b23-27b40c2a3b33",
      "acl":
      {
        "read":{},
        "write":{}
      }
    }

**Comment by fbuecklers** [comment]
Yeah, thats right and the issue is on our side. 
We have distributed a old version of our baqend SDK within the tutorial app. 
To fix your issue you must update the baqend.min.js in the libs folder with the latest one.
Here is a quick link to gate the latest minified version: https://raw.githubusercontent.com/Baqend/js-sdk/f6692c55504ccc09724dfd189715129282cf6910/dist/baqend.min.js

Hope that helps :-)

**Comment by TiJac** [comment]
Yes, it works now. Thank you

**Comment by fbuecklers** [comment]
Fine, in the next release it shoud be fixed.
And thanks :-)
