### ISSUE TITLE
How to set collections with references to other models

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/guide#3]
Hey there,

i do not know if this is the correct place to ask, but so it is (^^).

I want to add data to a collection through your baqend webinterface.
E.g. i have the models "Post" and "Tag"

Post has an attribute "tags" as a set of tag references.
Now how can i add values to this set?

i tried simply pasting the id of the tag with '/db/tags/id' or simply the id or trying new Set(...) and [...] because it is a set. but nothing works.

Thanks for your help.

Greets Bengt

**Comment by fbuecklers** [comment]
You can also use stackoverflow with the baqend tag ;-)

To save a set of references provide them just with:
`["/db/Tag/831e6cbf-ba12-4f1d-b020-6331717d0434"]`
